---
title: "Twitter Profile Analyzer"
#author: "Mario Ezekiel H. (m-ezekiel.com)"
#date: "Summer/Fall, 2017"
output: html_document
---

###### *Note that these statistics include both retweets and replies which have been posted to the user's timeline.

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
# Source files
source('Functions/twitterConfig.R')
source('Functions/userTimeline_stats_fXn.R')
```

```{r, echo=FALSE}
# Setup
userName <- "WolfieChristl"
n <- 10
user <- getUser(userName)
```


## <span style="color:#336699">`r paste0("@", userName, " :: ", n, " most recent tweets.")`</span>
#### <span style="color:#336699">`r user$description`</span>
##### `r paste0("URL: ", user$url)`
##### `r paste0("Created: ", user$created)`


```{r, echo=FALSE}
# Basic stats table
stats_tbl <- data.frame(tweets=user$statusesCount, 
                        friends=user$friendsCount,
                        followers=user$followersCount,
                        likes=user$favoritesCount,
                        listed=user$listedCount,
                        verified=user$verified,
                        protected=user$protected)
stats_tbl
```


```{r, echo=FALSE}
# Calculate account age for post frequency
created <- as.Date(user$created, format = "%Y-%m-%d")
today <- Sys.Date()
account_age <- as.numeric(today - created)

dailyPosts <- signif(user$statusesCount / account_age, 2)

# Derived stats table
derived_tbl <- data.frame(influence=round(user$followersCount/user$friendsCount),
                          dailyPosts=dailyPosts,
                          interactionLvl="")
derived_tbl
```


```{r, echo=FALSE}
# Hashtags table
Hashtags <- userTimeline_stats_fXn(userName, n, replies = FALSE)
# Engagement table
Engagement <- sort(userTimeline_stats_fXn(userName, n, replies = TRUE))

# Engagement user descriptions
for(i in 1:length(Engagement)) {
  print(paste0("@", Engagement[i]))
  try(print(getUser(Engagement[i])$description))      # Use try to skip errors
  print(NULL)
}
```

